{
        .name = "contaminate_mem",
        .args_type  = "addr:l,range:l,contaminate:l",
        .params     = "addr range contaminate",
        .help       = "contaminate a byte in memory",
        .mhandler.cmd = do_memory_contaminate,
},
{
        .name = "show_memory_taint_map",
        .args_type  = "addr:l,len:l",
        .params     = "addr len",
        .help       = "Show memory taint map",
        .mhandler.cmd = do_show_memory_taint_map,
},
{
        .name = "get_physic_address",
        .args_type  = "cr3:l,addr:l",
        .params     = "cr3 addr",
        .help       = "get the physic address of a given virtual address in memory space(cr3)",
        .mhandler.cmd = do_get_physic_address,
},
{
        .name = "enable_dift",
        .args_type  = "",
        .params     = "",
        .help       = "enable DIFT taint analysis",
        .mhandler.cmd = do_enable_dift,
},
{
        .name = "disable_dift",
        .args_type  = "",
        .params     = "",
        .help       = "disable DIFT taint analysis",
        .mhandler.cmd = do_disable_dift,
},
{
        .name = "dift_status",
        .args_type  = "",
        .params     = "",
        .help       = "show DIFT status (enabled/disabled)",
        .mhandler.cmd = do_dift_status,
},

